// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ✅ PRODUCTION: Credentials externalisées vers variables d'environnement
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vexgjrrqbjurgiqfjxwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZleGdqcnJxYmp1cmdpcWZqeHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzI0NDEsImV4cCI6MjA3MjQ0ODQ0MX0.nuyS9qkvIQ9FaL797kxhGFobZRshJXGZSyiCiOZ7cLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});